Throw
	A palavra reservada throw, é utilizada para lançar um erro dentro de um método.
	É utilizado para erros não checados. Erros que ocorrem durante a execução da aplicação. 
	Para errors que ocorrem durante a compilação, erros que a IDE checa. É necessário colocar a palavra reservada throws no plural na assinatura do método.

	//Checado
	static void gerarError() throws Exception{
		throw new Exception("Ocorreu um erro aqui!");
	}
	
	//Não checado
	static void gerarError() {
		throw new RuntimeException("Ocorreu um erro aqui!");
	}

	try {
		gerarError();
	} catch(RuntimeException e) {
		sysout(e.getMessage());
	}

Quando a excessão é checada, o métodeo que for chamar está função, é obrigado a utilizar o bloco try catch para tratar o erro.
	Resumo qualquer exception que seja filho de RunttimeException, será uma uma excessão não checada. Ou seja, não será obrigatório tratar este erro.
	Para Excessões que sejam filho diretos de Exception, o tratamento com try catch em algum momento quando o método é chamado é obrigatório. Se o error não for tratado o erro deve ser propagado para frente com o trhows.